### ISSUE TITLE
SDHC dualcore 2013 

### ISSUE THREAD

**Issue by bbheko25** [jason0597/ntrboot_flasher_nds#13]
I cant get this to work on my sdhc dualcore 2013 it says Flashcart setup failed

**Comment by jason0597** [comment]
What's the URL that's printed on the sticker on your flashcart?

**Comment by bbheko25** [comment]
Www.r4isdhc.com

**Comment by jason0597** [comment]
r4isdhc.com flashcarts that came out before 2014 are unsupported by flashcart_core at the time of writing this (13/12/2017)

**Comment by bbheko25** [comment]
https://imgur.com/gallery/F3o18

**Comment by jason0597** [comment]
As I said:

![img](https://image.prntscr.com/image/NkEyRSSrQUeHdhGrKvLHRw.png)

**Comment by bbheko25** [comment]
Aw need to buy a new one then

**Comment by jason0597** [comment]
If you need more help regarding what to do, ask [here](http://gbatemp.net/threads/3ds-noob-paradise-ask-questions-here.359035/)

Because this has nothing to do with this software, I am closing this issue.
